### ISSUE TITLE
dependencies issues when using jberet-support in quarkus 

### ISSUE THREAD

**Issue by cedricwalter** [jberet/jberet-support#2]
just adding

```
        <dependency>
            <groupId>org.jberet</groupId>
            <artifactId>jberet-support</artifactId>
            <version>1.4.0.Beta1</version>
        </dependency>
```

and it crash at start of quarkus with
```
Caused by: java.lang.ClassNotFoundException: com.datastax.driver.core.Statement
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
```

it is now asking for all dependencies of  jberet-support...why?
it this project still running or maintained?
thanks

**Comment by chengfang** [comment]
`jberet-support` contains some common components, some of which may not be used by your applications. Usaully these runtime dependency shouldn't cause problem, but given how Quarkus builds and loads classes and dependencies, you'll need to be careful which deps to bring in.  Check your apps deps `mvn dependency:tree`, and include only those necessary ones.

If that still doesn't solve it, you can try assemble a jar with selected components from jberet-support. If this becomes a common problems for users, we can consider breaking up jberet-support and release them as independent libs.

**Comment by cedricwalter** [comment]
thanks for the quick answer, I tried to exclude most dependencies that i don't need to use, without success

```
        <dependency>
            <groupId>org.jberet</groupId>
            <artifactId>jberet-support</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.mongodb</groupId>
                    <artifactId>mongo-java-driver</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.mongojack</groupId>
                    <artifactId>mongojack</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.hibernate.javax.persistence</groupId>
                    <artifactId>hibernate-jpa-2.1-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml</groupId>
                    <artifactId>aalto-xml</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.codehaus.woodstox</groupId>
                    <artifactId>stax2-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.poi</groupId>
                    <artifactId>poi</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.poi</groupId>
                    <artifactId>poi-ooxml</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.poi</groupId>
                    <artifactId>poi-ooxml-schemas</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.kafka</groupId>
                    <artifactId>kafka-clients</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.hibernate</groupId>
                    <artifactId>hibernate-validator</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.validation</groupId>
                    <artifactId>validation-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.hibernate</groupId>
                    <artifactId>hibernate-validator</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.glassfish</groupId>
                    <artifactId>javax.el</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>net.sf.jasperreports</groupId>
                    <artifactId>jasperreports</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.datastax.cassandra</groupId>
                    <artifactId>cassandra-driver-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.jboss.spec.javax.ws.rs</groupId>
                    <artifactId>jboss-jaxrs-api_2.0_spec</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.activemq</groupId>
                    <artifactId>artemis-jms-server</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.hibernate</groupId>
                    <artifactId>hibernate-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

but as soon as the jar load, it still complain with 

`Caused by: java.lang.NoClassDefFoundError: org/apache/activemq/artemis/api/core/ActiveMQException`

I see also that the parent of  jberet-support is 

```
    <parent>
        <groupId>org.jberet</groupId>
        <artifactId>jberet-parent</artifactId>
        <version>1.4.0.Alpha</version>
    </parent>
```

while the one of quarkus-jberet is

```
 <parent>
        <groupId>io.quarkiverse.jberet</groupId>
        <artifactId>quarkus-jberet-core-parent</artifactId>
        <version>0.0.3</version>
    </parent>
```

so If I start to extract JDBCReader/JDBCWriter out of jberet-support i might also have to deal with version clashes of classloader issues.

I would be maybe easier to move code to quarkus-jberet main repo. It is bad for modularization but would force to maintains these readers/writers and have them part of the quarkus-jberet build loop

**Comment by cedricwalter** [comment]
I'm trying another route for now, I did copy 

```
JCsvProperties
ItemReaderWriterBase
JdbcItemReader
JdbcItemReaderWriterBase
JdbcItemWriter
JsonItemReaderWriterBase
SupportMessages
UnicodeBOMInputStream
```

solve all import and compile error, use my own logger instead of  org.jberet.support._private.SupportLogger

and it is working! I hope that help others coming here

**Comment by cedricwalter** [comment]
I started working on splitting jberet-support to be able tp release them as independent libs. A PR should follow sometimes later
